### ISSUE TITLE
tkinter error 

### ISSUE THREAD

**Issue by Yn-Skr** [Cyborg117/PersonGen#1]
from tkinter import *
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'

**Comment by DonMiller9294** [comment]
The error you're encountering suggests that the `_tkinter` module, which is a core part of the Tkinter library in Python, is not available or properly configured in your Python installation. To resolve this issue, you can follow these steps:

1. **Check Python Version**: Ensure that you are using a Python version that includes Tkinter by default. Tkinter is usually bundled with the standard Python distribution. To check your Python version, open a terminal and run:

   ```bash
   python --version
   ```

   If you are using Python 3.x, Tkinter should be included. If you are using a custom Python distribution, consider switching to the system Python or a Python distribution that includes Tkinter.

2. **Reinstall Python**: If you're using a custom Python installation and Tkinter is missing, consider reinstalling Python from the official Python website (https://www.python.org/downloads/). Download and install the official Python distribution.

3. **Virtual Environments**: If you are working within a virtual environment, ensure that you have created the environment correctly and that Tkinter is available within it. Virtual environments do not always inherit packages from the system Python.

4. **System Dependencies**: On some systems, you may need to install additional system-level dependencies for Tkinter to work correctly. On Ubuntu or Debian-based systems, you can try installing the `tkinter` package:

   ```bash
   sudo apt-get install python3-tk
   ```

   This installs the necessary system libraries for Tkinter.

5. **macOS Note**: If you are using macOS, Tkinter should be available by default. However, you might encounter issues if you are using a custom Python distribution. Consider using the system Python or installing Python via a package manager like Homebrew.

6. **Windows Note**: On Windows, Tkinter should be available by default when you install Python from the official website. Ensure that you are using an official Python distribution and not a modified version.

After trying these steps, open a new terminal and test whether Tkinter is available by running a simple script:

```python
import tkinter as tk
root = tk.Tk()
root.mainloop()
```

If this script runs without errors and displays an empty Tkinter window, then Tkinter is working correctly in your Python environment.

If you continue to experience issues, please provide more details about your Python environment and how it was set up, including the operating system you're using, so that I can provide further assistance.

**Comment by Yn-Skr** [comment]
Thanks for the solution I run macOS 14.0 so I installed the python-tk package using brew: `brew install python-tk`. that fixed it
